apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssh-key
  namespace: jenkins
data:
  id_rsa: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNESmpxS01UZWJ6UFJVSkNNa0xkR0hrc0xjWkV0aEw0ZnMxVWFESG5RbDk5Z0FBQUpoa3VTM1BaTGt0Cnp3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREpqcUtNVGVielBSVUpDTWtMZEdIa3NMY1pFdGhMNGZzMVVhREhuUWw5OWcKQUFBRUFIMWlNZzN2NzUxcUxER0ZKeU93T2lWQ1hhYXg5bVk5dVBEcjdZcFJmYklNbU9vb3hONXZNOUZRa0l5UXQwWWVTdwp0eGtTMkV2aCt6VlJvTWVkQ1gzMkFBQUFGV0poWTI5dVFHSmhZMjl1TFhkdmNtdHpjR0ZqWlE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  id_rsa.pub: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU1tT29veE41dk05RlFrSXlRdDBZZVN3dHhrUzJFdmgrelZSb01lZENYMzIK
